source ~/.local/share/calos/default/bash/rc

function y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  yazi "$@" --cwd-file="$tmp"
  IFS= read -r -d '' cwd <"$tmp"
  [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
  rm -f -- "$tmp"
}

bind 'set show-all-if-ambiguous on'
bind 'TAB:menu-complete'

alias la='eza --icons=auto -a'
alias ls='eza --icons=auto'
alias grep='grep --color=auto'
alias dota='steam steam://rungameid/570/'
alias please='sudo'
alias cat='bat --style grid,header,header-filename,header-filesize '
alias update='sudo pacman -Syu'
alias upgrade='sudo pacman -Syu'
alias svim='sudoedit '

if ! systemctl is-active --quiet bootmsg; then
  fastfetch
  echo
  echo "Welcome to $HOSTNAME! Running initial startup scripts and daemon diagnostics:"
  pamixer --set-volume 80
  systemctl --failed
  echo
  sudo systemctl start bootmsg.service
  echo "Todays quote is:"
  fortune
  echo
  echo "happy autisming"
  echo
fi

# Set up fzf key bindings and fuzzy completion
eval "$(fzf --bash)"

export STARSHIP_CONFIG=~/.config/starship.toml
