source ~/.local/share/calos/bash/rc

# set up fzf key bindings and fuzzy completion

eval "$(fzf --bash)"

# yazi key functionality improvement

function y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  yazi "$@" --cwd-file="$tmp"
  IFS= read -r -d '' cwd <"$tmp"
  [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
  rm -f -- "$tmp"
}

# terminal upgrades

bind 'set show-all-if-ambiguous on'
bind 'TAB:menu-complete'
mkcd() { mkdir "$1" && cd "$1"; }

# aliases

alias oops='sudo $(history -p !!)'
alias la='eza --icons=auto -a'
alias ls='eza --icons=auto'
alias grep='grep --color=auto'
alias please='sudo'
alias cat='bat --style grid,header,header-filename,header-filesize '
alias update='sudo pacman -Syu'
alias upgrade='sudo pacman -Syu'
alias svim='sudoedit '
alias packages='calos-pkg-list'
# alias weather='curl wttr.in/[ADD_CITY_HERE]?format=3'

# first terminal boot service

if ! systemctl is-active --quiet bootmsg; then
  sleep 2
  fastfetch
  echo
  echo "Welcome to $HOSTNAME! Running initial startup scripts and daemon diagnostics:"
  pamixer --set-volume 80
  systemctl --failed
  echo
  sudo systemctl start bootmsg.service
  echo
  echo "Todays quote is:"
  fortune
  echo
  echo "happy autisming"
  echo
fi

# starship config

export STARSHIP_CONFIG=~/.config/starship.toml
