sudo pacman -S --noconfirm --needed \
  alacritty \
  avahi \
  bash-completion \
  bat \
  bluetui \
  brightnessctl \
  btop \
  cava \
  dust \
  eza \
  fortune-mod \
  fastfetch \
  fd \
  firefox \
  fzf \
  gnome-themes-extra \
  gum \
  hyprland \
  hypridle \
  hyprland-qtutils \
  hyprpicker \
  hyprshot \
  hyprsunset \
  inetutils \
  kvantum-qt5 \
  lazygit \
  less \
  llvm \
  mako \
  man \
  mise \
  noto-fonts \
  noto-fonts-cjk \
  noto-fonts-emoji \
  noto-fonts-extra \
  nss-mdns \
  nvim \
  omarchy-chromium \
  pamixer \
  playerctl \
  plocate \
  polkit-gnome \
  power-profiles-daemon \
  python-gobject \
  python-terminaltexteffects \
  ripgrep \
  satty \
  slurp \
  starship \
  swaybg \
  swayosd \
  tldr \
  tree-sitter-cli \
  ttf-cascadia-mono-nerd \
  ttf-font-awesome \
  ttf-jetbrains-mono \
  unzip \
  uwsm \
  walker-bin \
  waybar \
  whois \
  wiremix \
  wireplumber \
  wl-clip-persist \
  wl-clipboard \
  wl-screenrec \
  xdg-desktop-portal-gtk \
  xdg-desktop-portal-hyprland \
  xmlstarlet \
  yaru-icon-theme \
  yazi \
  yay \
  zoxide
