sudo pacman -S --noconfirm --needed \
  alacritty \
  bash-completion \
  bat \
  bluetui \
  btop \
  cava \
  cmus \
  dust \
  eza \
  fortune-mod \
  fastfetch \
  fd \
  firefox \
  fzf \
  greetd \
  greetd-tuigreet \
  hyprland \
  hypridle \
  hyprland-guiutils \
  hyprpicker \
  hyprshot \
  hyprsunset \
  inetutils \
  impala \
  mako \
  noto-fonts \
  noto-fonts-cjk \
  noto-fonts-emoji \
  noto-fonts-extra \
  nvim \
  pamixer \
  pinta \
  playerctl \
  plocate \
  pqiv \
  hyprpolkitagent \
  ripgrep \
  slurp \
  starship \
  swaybg \
  swayosd \
  tldr \
  tree-sitter-cli \
  ttf-cascadia-mono-nerd \
  ttf-font-awesome \
  uwsm \
  waybar \
  wiremix \
  wireplumber \
  wl-clip-persist \
  wl-clipboard \
  xdg-desktop-portal-gtk \
  xdg-desktop-portal-hyprland \
  yazi \
  7zip \
  zoxide
